global:
  scrape_interval: 6s

scrape_configs:
  - job_name: "api-gestao-vagas"
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["172.23.44.109:8080"]
        labels:
          application: "api-gestao-vagas"
          
